language: node_js
cache: yarn
node_js:
  - '8'
sudo: false
before_deploy:
  - npm run build
  - cd dist
script:
  - npm run test
after_script:

deploy:
- provider: npm
  email: devmonk@mediamonks.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    node: '8'
  skip_cleanup: true
notifications:
  slack:
    secure: QF2D6UwIxKX44jAsnlbeQMQbJIKGUxwUf0eS8FdVKBg0N0tVQwyzRDmBB94egC8/gft/kc5k52Y1sIJrpZY13QiaSTv3awxzbkUjIumWEUsg7fDZGu+hEQglWLGZ/XWrgoyjanjvzJD7cIyDv+dPzRnPq8YII54m52O/bfSPPjyJz35kAqyxipulxJn2FbTVKebBRRUjwqP2XyEx/YkpyUvtEKW18AYAHkmpEuGh9Zb9RavLq2IKDqjDt7qIffM24IH4G9TGY4VuwI2CU1xqwmN2E4oKW6NhREI3Vr13dZaa+Vr9GqJLHLV7gMNIKDiHzxWy5nWylUrGn+iKW3UwJYPrIYaU8wz1zzvMSFG9wPCGqhfLXJgFUhtPtcjDRcLy4uH3SK17xui6wEGEkDHqvI3NVhUHpp8dbssGtQtEE0mgMqszz1ULY+LJEJlNBQoVqbNO5XB/JKGXaVqVjjZQqLj8TIgFZUwbHHUrc2pTMV9AVDjkeJtMs6omPEtMzWMocOWNKlffV7mn7n6M7Ja5tlWhzsmpYprFiHmSqMYk1PVwBUC1XPmHxWO4oPeMzKXTLJqRHzRW5HReBbfS7pvnvKxq5BMJ/k/BhzobpVkf+fsTdtY2xlZxk5vhoXoAlyXihlGGuDiXzeVZ+/SGEL8LqbtkbuNJ0xsyCZnFtkQfcjQ=
